### ISSUE TITLE
"ploomber scaffold" should create missing modules when scaffolding functions

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#332]
If `ploomber scaffold` finds a `pipeline.yaml` it checks all `tasks[*].sources` and creates files for all tasks whose source is missing. e.g.,

```yaml
tasks:
    - source: some_module.some_function
      product: output.csv
```

If `some_module.py` exists, `ploomber scaffold` adds a function definition there. However, if it doesn't, it fails.

Calling the command should create all necessary modules. Note that this could be a nested module. e.g.,

```yaml
tasks:
    - source: some_module.submodule.function
      product: output.csv
```

This must create `some_module/` (directory), `some_module/__init__.py`, and `some_module/submodule.py`, the call the already implemented logic to create a function inside `some_module/submodule.py`.

`loader.create` implements the file creation logic: https://github.com/ploomber/ploomber/blob/ac915ea998f4da0177204f2189f8f608f3404fc6/src/ploomber/scaffold/__init__.py#L42

add tests here: https://github.com/ploomber/ploomber/blob/master/tests/cli/test_scaffold.py

## Tasks

- [x] Implement 'skip' logic to DAGSpec and TAskSpec: passing `lazy_import='skip'` should not perform any dotted paths validation and add tests with `lazy_import='skip'`
- [x] Implement `ploomber scaffold` feature that creates missing modules
- [ ] Rename `lazy_import` flag (not sure about what would be a good name, maybe `import_mode`?)

Please open a PR with `scaffold-functions` as the base branch after finishing any of the three tasks above so we can review it and move to the next one.

**Comment by fferegrino** [comment]
happy to pick this up, seems like a good place to learn more about the inner workings of ploomber

**Comment by edublancas** [comment]
Awesome! Feel free to ping me if you have questions

**Comment by fferegrino** [comment]
Just got round to this.

Upon further investigation, it seems that this requires changes to the behaviour of `TaskSpec`, specifically here:

https://github.com/ploomber/ploomber/blob/37f57e7462146452debec24ce13701349fa4ed31/src/ploomber/spec/taskspec.py#L181-183

As the intialisation fails here (but fails since the module does not actually exist): 

https://github.com/ploomber/ploomber/blob/37f57e7462146452debec24ce13701349fa4ed31/src/ploomber/spec/taskspec.py#L77-L78

All this stems from the fact that we are trying to load the `DAGSpec` while scaffolding, which triggers all the validations related to it:

https://github.com/ploomber/ploomber/blob/37f57e7462146452debec24ce13701349fa4ed31/src/ploomber/cli/cli.py#L63

------

I could write some code to bypass that limitation in `TaskSpec`, though I am not sure whether that is what we want since it seems `TaskSpec` is a cornerstone of Ploomber.

**Comment by edublancas** [comment]
Thanks for doing this! Yes, you're right. The current implementation checks that the function is importable because initially we didn't have a scaffold command and every DAGSpec/TaskSpec was expected to be fully specified.

I think it's ok to relax that restriction now to accommodate the scaffold feature, we already have a `lazy_import` flag, which we use to tell `DAGSpec` not to import modules, but it still verifies that they exist.

So I'm thinking maybe we can turn that `lazy_import` into a flag that has three modes:

Current:
1. `False` - no lazy import. import whatever you need to
2. `True` - lazy import. do not import but check that the dotted paths are importable

New:
3. `'skip'` - don't verify anything

So the first step would be to add the `'skip'` logic, then we can make sure all the tests pass, and add a few new ones to test `skip`.

With that change, you should be in good shape to implement the new scaffold feature.

The final step would be to rename the flag because `lazy_import` wouldn't be appropriate anymore.

What do you think?

**Comment by fferegrino** [comment]
Sounds good to me. Would you like to create separate issues for those changes or should I create them myself? I am also cool with taking over the responsibility of implementing them, and then come back to this one.

**Comment by edublancas** [comment]
Hi @fferegrino, thanks a lot for taking this one! I updated the issue's description with more details. Let me know if you have any questions.

**Comment by fferegrino** [comment]
Cool!

**Comment by fferegrino** [comment]
Hey @edublancas, I've opened this one: https://github.com/ploomber/ploomber/pull/430

**Comment by edublancas** [comment]
Awesome! Give me a few days to take a look a this. Thanks a lot for working on this!

**Comment by fferegrino** [comment]
I've got the second PR lined up here: https://github.com/fferegrino/ploomber/pull/1

**Comment by edublancas** [comment]
Awesome! Please submit the PR

**Comment by edublancas** [comment]
Awesome, I just merged #436! Now, for the last item. what do you think? Should we rename `lazy_import` for something else? If so, what would it be a good name?

I think `import_mode` makes sense:

* `eager` (default, import everything)
* `lazy` (import only when needed)
* `skip` (do not import anything)

We have the policy to show warnings during two minor versions whenever we introduce breaking changes. So #436 can go in the next minor release, but if we decide to rename, I can merge the PR, but will keep it until the next major release.

**Comment by fferegrino** [comment]
I like `import_mode` since `lazy_import='skip'` sounds like saying "eager mode". 

I'll open a PR adding the argument and a warning telling people that `lazy_import` is now deprecated (if they use it), we can then make that change in the next major release, sounds good?

**Comment by edublancas** [comment]
Sounds good, thanks! Here's [the guide we follow](https://scikit-learn.org/stable/developers/contributing.html#maintaining-backwards-compatibility)

Please add the `FutureWarning` thing and a little note in the docstring. This will be part of release `0.14` and we'll apply the renaming in version `0.16`.

**Comment by edublancas** [comment]
FYI, I merged your latest PR to master 🎉 @fferegrino
