### ISSUE TITLE
User guide on report generation

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#676]
People are using Ploomber to generate reports from notebooks, however, there isn't a guide showing how to customize the final report, we should add one.

Things to cover:

- [x] how to hide code (only display results)
- [x] selectively hide a few sells ([see here](https://github.com/ploomber/ploomber/issues/658#issuecomment-1074701673))
- [x] how to choose the PDF engine (this is an open issue #675)
- [ ] generating multiple formats (open issue #673)
- [x] using ScriptRunner
- [ ] link this new doc section from the Jupyter integration one
- [ ] link this new doc section from the YAML API
